DEFAULT_FONT = ("Helvetica", 11)
DEFAULT_FONT_2 = ("Helvetica", 11)
ERROR_FONT_LARGE = ("Helvetica", 30)
ERROR_FONT = ("Helvetica", 12)
ERROR_FONT_SMALL = ("Helvetica", 10)
ERROR_FONT_UNDERLINE = ("Helvetica", 10, "underline")
