DEFAULT_FONT = ("나눔스퀘어_ac Bold", 11)
DEFAULT_FONT_2 = ("나눔스퀘어_ac Bold", 10)
ERROR_FONT_LARGE = ("나눔스퀘어_ac Bold", 30)
ERROR_FONT = ("나눔스퀘어_ac Bold", 12)
ERROR_FONT_SMALL = ("나눔스퀘어_ac Bold", 10)
ERROR_FONT_UNDERLINE = ("나눔스퀘어_ac Bold", 10, "underline")
